Repository banyandata-cloud/roots, pull requests merged in 2023-09, with the labels that each got.

#328 Storybook Documentation | UT-19
  .env
  components/alert/Alerts.stories.jsx
  components/alert/Alerts.stories.mdx
  components/breadcrumbs/Breadcrumbs.stories.jsx
  components/breadcrumbs/Breadcrumbs.stories.mdx
  components/buttons/baseButton/BaseButton.jsx
  components/buttons/baseButton/BaseButton.stories.jsx
  components/buttons/baseButton/BaseButton.stories.mdx
  components/buttons/button/Button.jsx
  components/buttons/button/Button.stories.jsx
  components/buttons/button/Button.stories.mdx
  components/buttons/chip/Chip.jsx
  components/buttons/chip/Chip.stories.jsx
  components/buttons/chip/Chip.stories.mdx
  components/codeSnippet/CodeSnippet.jsx
  components/datePicker/DatePicker.jsx
  components/datePicker/DatePicker.module.css
  components/datePicker/DatePicker.stories.mdx
  components/hierarchy/browser/HierarchyBrowser.jsx
  components/hierarchy/browser/HierarchyBrowser.stories.jsx
  components/hierarchy/browser/HierarchyBrowser.stories.mdx
  components/hierarchy/item/HierarchyItem.jsx
  components/hierarchy/item/HierarchyItem.stories.jsx
  components/hierarchy/item/HierarchyItem.stories.mdx
  components/icons/Arrow/Arrow.jsx
  components/icons/Calender/Calender.jsx
  components/icons/Copy/Copy.jsx
  components/input/checkbox/CheckBox.jsx
  components/input/checkbox/CheckBox.stories.jsx
  components/input/checkbox/CheckBox.stories.mdx
  components/input/dropdown/Dropdown.jsx
  components/input/dropdown/Dropdown.stories.jsx
  components/input/dropdown/Dropdown.stories.mdx
  components/input/radio/Radio.jsx
  components/input/radio/Radio.stories.jsx
  components/input/radio/Radio.stories.mdx
  components/input/slider/Slider.jsx
  components/input/switch/Switch.jsx
  components/input/switch/Switch.stories.jsx
  components/input/switch/Switch.stories.mdx
  components/input/textField/TextField.jsx
  components/input/textField/Textfield.stories.jsx
  components/input/textField/Textfield.stories.mdx
  components/maps/Map/Map.stories.jsx
  components/maps/Map/Map.stories.mdx
  components/modal/BaseModal.stories.jsx
  components/modal/BaseModal.stories.mdx
  components/modal/dialogBox/Dialog.stories.jsx
  components/modal/dialogBox/Dialog.stories.mdx
  components/pageHeader/PageHeader.stories.jsx
  components/pageHeader/PageHeader.stories.mdx
  components/pagination/Pagination.stories.jsx
  components/pagination/Pagination.stories.mdx
  components/stepper/Stepper.stories.jsx
  components/stepper/Stepper.stories.mdx
  components/stepper/step/Step.stories.jsx
  components/stepper/step/Step.stories.mdx
  components/tabs/Tabs.stories.jsx
  components/tabs/Tabs.stories.mdx
  pnpm-lock.yaml
Labels: documentation, enhancement

#336 Updated Datepicker, Toggle and Dropdown 🎨
  components/Toggle/Toggle.module.css
  components/Toggle/Toggle.module.scss
  components/accordion/Accordion.module.css
  components/buttons/baseButton/BaseButton.module.css
  components/datePicker/DatePicker.module.css
  components/datePicker/DatePicker.module.scss
  components/datePicker/DatePicker.stories.mdx
  components/datePicker/calender/Calender.module.css
  components/datePicker/calender/body/dates/Dates.module.css
  components/datePicker/calender/footer/Footer.module.css
  components/datePicker/calender/header/dateAndTimeSelection/DateAndTimeSelection.module.css
  components/hierarchy/browser/HierarchyBrowser.module.css
  components/hierarchy/item/HierarchyItem.module.css
  components/input/checkbox/CheckBox.module.css
  components/input/dropdown/Dropdown.module.css
  components/input/dropdown/Dropdown.module.scss
  components/input/radio/Radio.module.css
  components/input/switch/Switch.module.css
  components/input/textField/TextField.module.css
  components/pagination/Pagination.module.css
  components/skeleton/Skeleton.module.css
  components/table/cell/TableCell.module.css
  components/table/table/Table.module.css
  components/table/table/tableChips/chipDropdown/ChipDropdown.module.css
  components/table/table/tableChips/tableChipItem/TableChipItem.module.css
  components/table/table/tableFilters/Filters/Columns/Columns.module.css
Labels: enhancement

#338 Storybook mdx
  components/charts/verticalBarChart/BaseVerticalBarChart.jsx
Labels: enhancement

#342 New Design Table Cell, Header and Row
  components/table/cell/TableCell.jsx
  components/table/cell/TableCell.stories.mdx
  components/table/header/TableHeader.jsx
  components/table/header/TableHeader.stories.mdx
  components/tableV2/cell/index.js
  components/tableV2/header/TableHeader.jsx
  components/tableV2/header/index.js
  components/tableV2/row/TableRow.jsx
Labels: enhancement

#346 Storybook mdx
  components/widget/BaseWidget.jsx
  components/widget/BaseWidget.module.css
  components/widget/BaseWidget.module.scss
Labels: enhancement

#348 Inlining Widget Option for all Filters
  components/widget/BaseWidget.jsx
  components/widget/BaseWidget.module.css
  components/widget/BaseWidget.module.scss
Labels: enhancement

#350 Table Filters
  components/icons/ColumnFilter/ColumnFilter.jsx
  components/icons/ColumnFilter/index.js
  components/icons/index.js
  components/table/cell/TableCell.jsx
  components/table/table/Table.stories.mdx
  components/tableV2/table/Table.jsx
  components/tableV2/table/tableFilters/TableFilters.jsx
  components/tableV2/table/tableFilters/TableFilters.module.css
  components/tableV2/table/tableFilters/TableFilters.module.scss
Labels: enhancement

#352 ✨ Breadcrumbs design updated
  components/breadcrumbs/Breadcrumbs.jsx
  components/breadcrumbs/Breadcrumbs.module.css
  components/breadcrumbs/Breadcrumbs.module.scss
  components/breadcrumbs/Breadcrumbs.stories.mdx
  components/icons/Arrow/Arrow.jsx
  components/icons/BreadcrumbSeperator/BreadcrumbSeperator.jsx
  components/icons/Home/Home.jsx
  components/icons/Home/index.js
  components/icons/Server/Server.jsx
  components/icons/index.js
Labels: enhancement

#354 :sparkles: Updated logic Breadcrumbs
  components/breadcrumbs/Breadcrumbs.jsx
Labels: enhancement

#358 🐛 Fixed breadcrumbs logic
  components/breadcrumbs/Breadcrumbs.jsx
  components/breadcrumbs/Breadcrumbs.stories.mdx
Labels: bug

#360 🐛 Fixed pagination spacing issue
  components/pagination/Pagination.jsx
  components/pagination/Pagination.module.css
  components/pagination/Pagination.module.scss
Labels: bug

#362 🐛 Pagination spacing issue
  components/pagination/Pagination.module.css
  components/pagination/Pagination.module.scss
Labels: bug

#364 ✨ Added modal side panel
  components/sidePanel/BaseSidePanel.jsx
  components/sidePanel/BaseSidePanel.module.css
  components/sidePanel/BaseSidePanel.module.scss
  components/sidePanel/BaseSidePanel.stories.mdx
Labels: enhancement

#367 🐛 Custom wrapper id - base side panel
  components/modal/BaseModal.jsx
  components/sidePanel/BaseSidePanel.jsx
Labels: bug

#369 :bug: Fixed wrapper id
  components/modal/BaseModal.jsx
  components/sidePanel/BaseSidePanel.jsx
Labels: bug

#371 🎨 Updated side panel width
  components/sidePanel/BaseSidePanel.module.css
  components/sidePanel/BaseSidePanel.module.scss
Labels: enhancement

#344 :recycle: Alert modal changes
  components/alert/Alert.jsx
  components/alert/Alert.module.css
  components/alert/Alert.module.scss
  components/alert/Alerts.stories.mdx
  components/buttons/button/Button.jsx
  components/buttons/button/Button.module.css
  components/buttons/button/Button.module.scss
  components/buttons/button/Button.stories.mdx
  components/icons/fullScreen/FullScreen.jsx
  components/icons/fullScreen/index.js
  components/icons/index.js
  components/index.js
  components/maps/Map/Map.jsx
  components/maps/Map/Mapv2.stories.mdx
  components/mapsV2/Map.jsx
  components/mapsV2/Map.module.css
  components/mapsV2/Map.module.scss
  components/mapsV2/config.js
  components/mapsV2/index.js
  components/mapsV2/tooltip/Tooltip.jsx
  components/mapsV2/tooltip/Tooltip.module.css
  components/mapsV2/tooltip/Tooltip.module.scss
  components/modal/BaseModal.jsx
  components/modal/BaseModal.module.css
  components/modal/BaseModal.module.scss
  components/modal/dialogBox/Dialog.module.css
  components/modal/dialogBox/Dialog.module.scss
  components/modal/dialogBox/Dialog.stories.mdx
  components/modal/dialogBox/DialogBox.jsx
  components/tableV2/cell/TableCell.module.css
  package.json
  pnpm-lock.yaml
Labels: enhancement
