Repository banyandata-cloud/roots, pull requests merged in 2024-07, with the labels that each got.

#610 Aryan roots dev
  components/datePicker/DatePicker.jsx
  components/datePicker/DatePicker.stories.mdx
  components/datePicker/calender/header/Header.jsx
  components/datePicker/calender/header/dateAndTimeSelection/DateAndTimeSelection.jsx
  components/datePicker/timeSwitcher/TimeSwitcher.jsx
  components/datePicker/utils/index.js
  components/pagination/Pagination.jsx
  components/table/table/Table.stories.mdx
Labels: bug, enhancement

#615 Aryan roots dev
  components/datePicker/DatePicker.jsx
  components/datePicker/clockView/ClockView.jsx
  components/datePicker/timeSwitcher/TimeSwitcher.jsx
  components/datePicker/utils/index.js
Labels: bug

#623 :recycle: Modal refactoring
  components/modal/BaseModal.jsx
Labels: enhancement
